name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        # env:
        #   databricks: ${{ secrets.ACCESS_TOKEN}}
        #   server_host: ${{ secrets.SERVER_HOSTNAME}}
        #   http_path: ${{ secrets.HTTP_PATH}}
        run: make test
      - name: format
        run: make format